import {
  customerRecords,
  dashboardActivities,
  dashboardCharts,
  dealPipelineCards,
  dispatchRecords,
  dispatchSummary,
  liveActivityLogs,
  paymentRecords,
  paymentSummary,
  pipelineStages,
  purchaseOrderRecords,
  quotationRecords,
  recentTransactionRecords,
  reportCards,
  taskRecords,
  todayTaskItems,
  revenueTrendPoints,
} from './mockData';

const baseStats = (first, second, third, fourth) => [first, second, third, fourth];

export const customersConfig = {
  kicker: 'Accounts',
  title: 'Customers',
  subtitle: 'A live customer register with clear ownership, activity, and billing visibility.',
  primaryAction: 'Add Customer',
  autosaveSeed: 'customers',
  stats: baseStats(
    { label: 'Customers', value: '128', change: 'Active accounts' },
    { label: 'Open Invoices', value: '24', change: 'Needs attention' },
    { label: 'High Priority', value: '8', change: 'Escalation list' },
    { label: 'This Month', value: '₹48.2L', change: 'Revenue tracked' },
  ),
  panelTitle: 'Customer operations',
  panelSubtitle: 'Everything a business user needs to act quickly',
  features: [
    'See ownership, city, and last activity without opening a record.',
    'Move from customer to follow-up or payment without friction.',
    'Keep payment exposure visible for faster decisions.',
  ],
  workflow: [
    { label: 'Active', value: '104', status: 'Completed' },
    { label: 'At Risk', value: '16', status: 'Overdue' },
    { label: 'New', value: '8', status: 'Pending' },
    { label: 'Paid', value: '72', status: 'Completed' },
  ],
  timeline: liveActivityLogs,
  table: {
    title: 'Customer Register',
    subtitle: 'Searchable business accounts with clear operational context',
    rows: customerRecords,
    columns: [
      { header: 'Company', accessor: 'company', sortable: true },
      { header: 'Contact', accessor: 'contact', sortable: true },
      { header: 'Owner', accessor: 'owner', sortable: true },
      { header: 'City', accessor: 'city', sortable: true },
      { header: 'Open Invoices', accessor: 'openInvoices', sortable: true },
      { header: 'Deal Value', accessor: 'dealValue', sortable: true },
      { header: 'Last Activity', accessor: 'lastActivity', sortable: true },
      { header: 'Status', accessor: 'status', sortable: true },
    ],
    filters: ['Pending', 'Completed', 'Overdue'],
    rowActions: [{ label: 'Open', onClick: () => {} }],
  },
};

export const tasksConfig = {
  kicker: 'Operations',
  title: 'Tasks',
  subtitle: 'Today’s business actions arranged for quick execution and easy follow-up.',
  primaryAction: 'Create Task',
  autosaveSeed: 'tasks',
  stats: baseStats(
    { label: 'Today', value: '5', change: 'Open items' },
    { label: 'Overdue', value: '1', change: 'Needs attention' },
    { label: 'Completed', value: '3', change: 'Already closed' },
    { label: 'Next 24h', value: '4', change: 'Scheduled' },
  ),
  panelTitle: 'Task workflow',
  panelSubtitle: 'Simple task handling for follow-ups and dispatches',
  features: [
    'Track due times, ownership, and customer linkage.',
    'Reduce missed follow-ups with one-screen visibility.',
    'Keep daily work organized by priority.',
  ],
  workflow: [
    { label: 'Pending', value: '2', status: 'Pending' },
    { label: 'Done', value: '3', status: 'Completed' },
    { label: 'Overdue', value: '1', status: 'Overdue' },
    { label: 'Today', value: '5', status: 'Completed' },
  ],
  timeline: liveActivityLogs,
  table: {
    title: 'Task Board',
    subtitle: 'Each row is an action the team can close fast',
    rows: taskRecords,
    columns: [
      { header: 'Task', accessor: 'task', sortable: true },
      { header: 'Customer', accessor: 'customer', sortable: true },
      { header: 'Owner', accessor: 'owner', sortable: true },
      { header: 'Due', accessor: 'due', sortable: true },
      { header: 'Status', accessor: 'status', sortable: true },
    ],
    filters: ['Pending', 'Completed', 'Overdue'],
  },
};

export const quotationConfig = {
  kicker: 'Sales',
  title: 'Quotations',
  subtitle: 'Quotation records with approval state, value, and conversion context.',
  primaryAction: 'Create Quotation',
  autosaveSeed: 'quotations',
  stats: baseStats(
    { label: 'Pending', value: '28', change: 'Awaiting approval' },
    { label: 'Sent Today', value: '12', change: 'Shared with customers' },
    { label: 'Win Rate', value: '71%', change: 'Current quarter' },
    { label: 'Due Soon', value: '8', change: 'Expires in 24h' },
  ),
  panelTitle: 'Quotation workflow',
  panelSubtitle: 'Clear pricing progression with minimal friction',
  features: [
    'Manage quote revision and approval states.',
    'Spot expiring quotations early.',
    'Keep pricing visible to the sales team.',
  ],
  workflow: [
    { label: 'Draft', value: '8', status: 'Pending' },
    { label: 'Sent', value: '12', status: 'Completed' },
    { label: 'Approved', value: '19', status: 'Completed' },
    { label: 'Expired', value: '3', status: 'Overdue' },
  ],
  timeline: liveActivityLogs,
  table: {
    title: 'Quotation Register',
    subtitle: 'All quotations in one readable ledger',
    rows: quotationRecords,
    columns: [
      { header: 'Quotation', accessor: 'quotation', sortable: true },
      { header: 'Customer', accessor: 'customer', sortable: true },
      { header: 'Amount', accessor: 'amount', sortable: true },
      { header: 'Validity', accessor: 'validity', sortable: true },
      { header: 'Owner', accessor: 'owner', sortable: true },
      { header: 'Approval', accessor: 'approval', sortable: true },
      { header: 'Status', accessor: 'status', sortable: true },
    ],
    filters: ['Pending', 'Completed', 'Overdue'],
  },
};

export const purchaseOrdersConfig = {
  kicker: 'Procurement',
  title: 'Purchase Orders',
  subtitle: 'PO monitoring with vendor and delivery context.',
  primaryAction: 'Create PO',
  autosaveSeed: 'purchase-orders',
  stats: baseStats(
    { label: 'Open POs', value: '24', change: 'Under review' },
    { label: 'Approved', value: '18', change: 'Released to vendor' },
    { label: 'Delivery', value: '21', change: 'On schedule' },
    { label: 'Value', value: '₹1.8Cr', change: 'Tracked this month' },
  ),
  panelTitle: 'PO workflow',
  panelSubtitle: 'Keep vendor handoff visible and easy to scan',
  features: [
    'Track vendor approval and delivery milestones.',
    'See linked sales order and transporter information.',
    'Reduce procurement follow-up friction.',
  ],
  workflow: [
    { label: 'Draft', value: '7', status: 'Pending' },
    { label: 'Approved', value: '18', status: 'Completed' },
    { label: 'Dispatched', value: '12', status: 'Completed' },
    { label: 'Awaiting', value: '5', status: 'Overdue' },
  ],
  timeline: liveActivityLogs,
  table: {
    title: 'Purchase Order Ledger',
    subtitle: 'Vendor progress and delivery readiness',
    rows: purchaseOrderRecords,
    columns: [
      { header: 'Order', accessor: 'order', sortable: true },
      { header: 'Customer', accessor: 'customer', sortable: true },
      { header: 'Sales Order', accessor: 'salesOrder', sortable: true },
      { header: 'Transporter', accessor: 'transporter', sortable: true },
      { header: 'Total', accessor: 'total', sortable: true },
      { header: 'Stage', accessor: 'stage', sortable: true },
      { header: 'Delivery', accessor: 'delivery', sortable: true },
      { header: 'Status', accessor: 'status', sortable: true },
    ],
    filters: ['Pending', 'Completed', 'Overdue'],
  },
};

export const dispatchConfig = {
  kicker: 'Logistics',
  title: 'Dispatch',
  subtitle: 'Vehicle allocation and delivery tracking with a direct route to daily execution.',
  primaryAction: 'Add Dispatch',
  autosaveSeed: 'dispatch',
  stats: baseStats(
    { label: 'Dispatches Today', value: '17', change: 'Planned' },
    { label: 'In Transit', value: '3', change: 'Currently moving' },
    { label: 'Delivered', value: '12', change: 'Confirmed' },
    { label: 'Delayed', value: '2', change: 'Needs attention' },
  ),
  panelTitle: 'Dispatch workflow',
  panelSubtitle: 'Keep logistics teams informed with low-friction controls',
  features: [
    'Plan dispatches with route and dock visibility.',
    'Allocate vehicles according to payload and timing.',
    'Monitor loading progress with fewer handoffs.',
  ],
  workflow: [
    { label: 'Loading', value: '6', status: 'Pending' },
    { label: 'Dispatched', value: '14', status: 'Completed' },
    { label: 'Delayed', value: '2', status: 'Overdue' },
    { label: 'Delivered', value: '21', status: 'Completed' },
  ],
  timeline: liveActivityLogs,
  table: {
    title: 'Dispatch Register',
    subtitle: 'Route, ETA, and invoice status at a glance',
    rows: dispatchRecords,
    columns: [
      { header: 'Dispatch', accessor: 'dispatch', sortable: true },
      { header: 'Vehicle', accessor: 'vehicle', sortable: true },
      { header: 'Route', accessor: 'route', sortable: true },
      { header: 'Loading', accessor: 'loading', sortable: true },
      { header: 'Invoice', accessor: 'invoice', sortable: true },
      { header: 'ETA', accessor: 'eta', sortable: true },
      { header: 'Status', accessor: 'status', sortable: true },
    ],
    filters: ['Pending', 'Completed', 'Overdue', 'In Transit', 'Delivered'],
  },
};

export const paymentsConfig = {
  kicker: 'Finance',
  title: 'Payments',
  subtitle: 'Collections, receipts, and payment reminders with customer ledger context.',
  primaryAction: 'Payment Entry',
  autosaveSeed: 'payments',
  stats: baseStats(
    { label: 'Pending', value: '₹2.45L', change: 'Needs follow-up' },
    { label: 'Due Today', value: '₹1.24L', change: 'Escalation list' },
    { label: 'Collected', value: '₹18.4L', change: 'This week' },
    { label: 'Transactions', value: '41', change: 'Live entries' },
  ),
  panelTitle: 'Collections workflow',
  panelSubtitle: 'Simple finance operations for non-technical users',
  features: [
    'See pending, overdue, and collected amounts in one glance.',
    'Record receipts and send reminders quickly.',
    'Keep ledgers and profitability visible.',
  ],
  workflow: [
    { label: 'Pending', value: '9', status: 'Pending' },
    { label: 'Completed', value: '21', status: 'Completed' },
    { label: 'Overdue', value: '5', status: 'Overdue' },
    { label: 'Collected', value: '₹18.4L', status: 'Completed' },
  ],
  timeline: liveActivityLogs,
  table: {
    title: 'Payment Register',
    subtitle: 'Real-time payment and receipt tracking',
    rows: paymentRecords,
    columns: [
      { header: 'Receipt', accessor: 'receipt', sortable: true },
      { header: 'Customer', accessor: 'customer', sortable: true },
      { header: 'Amount', accessor: 'amount', sortable: true },
      { header: 'Mode', accessor: 'mode', sortable: true },
      { header: 'Ledger', accessor: 'ledger', sortable: true },
      { header: 'Profitability', accessor: 'profitability', sortable: true },
      { header: 'Status', accessor: 'status', sortable: true },
    ],
    filters: ['Pending', 'Completed', 'Overdue'],
  },
  form: {
    title: 'Payment Entry',
    subtitle: 'Capture the receipt and save automatically.',
    initialValues: {
      customer: 'Apex Steels Pvt Ltd',
      amount: '₹1,24,500',
      mode: 'NEFT',
      reference: 'PAY-2048',
    },
    fields: [
      { name: 'customer', label: 'Customer', placeholder: 'Select customer' },
      { name: 'amount', label: 'Amount', placeholder: 'Enter amount' },
      { name: 'mode', label: 'Mode', placeholder: 'NEFT, RTGS, Cheque, UPI' },
      { name: 'reference', label: 'Reference', placeholder: 'Enter payment reference' },
    ],
  },
};

export const reportsConfig = {
  kicker: 'Insights',
  title: 'Reports',
  subtitle: 'Action-oriented operational reports for sales, dispatch, and finance.',
  primaryAction: 'Generate Report',
  autosaveSeed: 'reports',
  stats: baseStats(
    { label: 'Lead Conversion', value: '38%', change: 'Best in 6 months' },
    { label: 'Quotation Win Rate', value: '71%', change: 'Up 9%' },
    { label: 'Dispatch SLA', value: '96%', change: 'On-time delivery' },
    { label: 'Collections', value: '₹2.1Cr', change: '87% recovered' },
  ),
  panelTitle: 'Reporting workflow',
  panelSubtitle: 'Keep executives focused on actionable KPIs',
  features: reportCards.map((card) => `${card.label}: ${card.note}`),
  workflow: [
    { label: 'Lead Conversion', value: '38%', status: 'Completed' },
    { label: 'Collections', value: '₹2.1Cr', status: 'Completed' },
    { label: 'Dispatch SLA', value: '96%', status: 'Completed' },
    { label: 'Vehicle Utilization', value: '84%', status: 'Pending' },
  ],
  timeline: liveActivityLogs,
  table: {
    title: 'Recent Transactions',
    subtitle: 'A concise operational report surface',
    rows: recentTransactionRecords.map((item) => ({
      ...item,
      item: item.reference,
    })),
    columns: [
      { header: 'Item', accessor: 'item', sortable: true },
      { header: 'Customer', accessor: 'customer', sortable: true },
      { header: 'Amount', accessor: 'amount', sortable: true },
      { header: 'Status', accessor: 'status', sortable: true },
      { header: 'Time', accessor: 'time', sortable: true },
    ],
    filters: ['Pending', 'Completed', 'Overdue'],
  },
};

export const settingsConfig = {
  kicker: 'Administration',
  title: 'Settings',
  subtitle: 'Company preferences, notifications, and operational defaults.',
  primaryAction: 'Save Preferences',
  autosaveSeed: 'settings',
  stats: baseStats(
    { label: 'Users', value: '42', change: 'Active' },
    { label: 'Notifications', value: 'On', change: 'Enabled' },
    { label: 'Roles', value: '18', change: 'Configured' },
    { label: 'Audit', value: 'Live', change: 'Realtime' },
  ),
  panelTitle: 'System preferences',
  panelSubtitle: 'Low-friction settings for day-to-day admins',
  features: [
    'Manage profile, roles, and notification defaults.',
    'Keep organization-wide options easy to understand.',
    'Autosave changes while editing.',
  ],
  workflow: [
    { label: 'Saved', value: 'Yes', status: 'Completed' },
    { label: 'Roles', value: '18', status: 'Pending' },
    { label: 'Audit', value: 'Live', status: 'Completed' },
    { label: 'Alerts', value: 'On', status: 'Completed' },
  ],
  timeline: liveActivityLogs,
  form: {
    title: 'Company Preferences',
    subtitle: 'Configuration stays simple and editable.',
    initialValues: {
      company: 'Atlas One Pvt. Ltd.',
      currency: 'INR',
      timezone: 'Asia/Kolkata',
      notifications: 'Enabled',
    },
    fields: [
      { name: 'company', label: 'Company Name', placeholder: 'Enter company name' },
      { name: 'currency', label: 'Currency', placeholder: 'INR' },
      { name: 'timezone', label: 'Timezone', placeholder: 'Asia/Kolkata' },
      { name: 'notifications', label: 'Notifications', placeholder: 'Enabled / Disabled' },
    ],
  },
};
